# Generated by Django 4.2 on 2023-11-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_general_models', '0007_alter_utilsector_sector_alter_utiltheme_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateCompanySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '企业及行业中间表',
                'verbose_name_plural': '企业及行业中间表',
                'db_table': 'intermediate_company_sector',
            },
        ),
        migrations.CreateModel(
            name='IntermediateCompanyTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '企业及热门主题中间表',
                'verbose_name_plural': '企业及热门主题中间表',
                'db_table': 'intermediate_company_theme',
            },
        ),
        migrations.CreateModel(
            name='SortCompanyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField()),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('description_zh_Hans', models.TextField(blank=True, max_length=4000, null=True)),
                ('description_de', models.TextField(blank=True, max_length=4000, null=True)),
                ('description_en', models.TextField(blank=True, max_length=4000, null=True)),
                ('established', models.IntegerField(blank=True, null=True)),
                ('num_staff', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_general_models.utilcity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_general_models.utilcountry')),
                ('sector', models.ManyToManyField(through='sort_company.IntermediateCompanySector', to='db_general_models.utilsector')),
                ('theme', models.ManyToManyField(through='sort_company.IntermediateCompanyTheme', to='db_general_models.utiltheme')),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业',
                'db_table': 'sort_company',
            },
        ),
        migrations.AddField(
            model_name='intermediatecompanytheme',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sort_company.sortcompanystore'),
        ),
        migrations.AddField(
            model_name='intermediatecompanytheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_general_models.utiltheme'),
        ),
        migrations.AddField(
            model_name='intermediatecompanysector',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sort_company.sortcompanystore'),
        ),
        migrations.AddField(
            model_name='intermediatecompanysector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_general_models.utilsector'),
        ),
    ]
