# Generated by Django 4.2 on 2023-11-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_general_models', '0008_alter_utilcity_city_cn'),
        ('sort_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intermediatecompanysector',
            unique_together={('company', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='intermediatecompanytheme',
            unique_together={('company', 'theme')},
        ),
    ]
