# Generated by Django 4.2 on 2023-11-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutSidebar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index_path', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=100)),
                ('path_level', models.IntegerField()),
                ('auth_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('parent_path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webmodule_sidebar.layoutsidebar')),
            ],
            options={
                'verbose_name': '前端侧边栏',
                'verbose_name_plural': '前端侧边栏',
                'db_table': 'webmodule_sidebar',
            },
        ),
    ]
