# Generated by Django 4.2 on 2023-11-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userstore_nickname_userstore_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstore',
            name='user_pic',
            field=models.CharField(blank=True, max_length=12000, null=True, verbose_name='头像'),
        ),
    ]
