"""
Django settings for cincode_backend project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from datetime import timedelta

AUTH_USER_MODEL = 'users.UserStore'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'app'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gj*h%*ex3ip*m!tc)8zv^vw+hiii7vv6)-3lknev14_j@j%e$&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.2.113']

# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt',
    'users.apps.UsersConfig',
    'article_cate.apps.ArticleCateConfig',
    'article.apps.ArticleConfig',
    'app.webmodule_sidebar',
    'exposition.apps.ExpositionConfig',
    'utils.db_general_models'

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # modeltranslation所需

]

# modeltranslation所需
gettext = lambda s: s
LANGUAGES = [
    ('zh-Hans', gettext('Chinese (Simplified)')),
    ('de', gettext('German')),
    ('en', gettext('English')),
    # 其他语言
]
# LANGUAGES = [
#     ('zh-Hans', 'Chinese (Simplified)'),
#     ('de', 'German'),
#     ('en', 'English'),
#     # 其他语言
# ]

# 配置 modeltranslation
# 配置 modeltranslation 使用 manual 模式
# MODELTRANSLATION_AUTO_POPULATE = 'manual' True False
MODELTRANSLATION_AUTO_POPULATE = False

# 默认语言
MODELTRANSLATION_DEFAULT_LANGUAGE = 'zh-Hans'
# 指定翻译语言
# 默认是汉语了，所以这里不需要添加汉语
MODELTRANSLATION_LANGUAGES = ('zh-Hans', 'de', 'en')
# 指定返回语言顺序  (注意返回语言必须在翻译上面一行的翻译语言的列表中)
MODELTRANSLATION_FALLBACK_LANGUAGES = ('zh-Hans', 'de', 'en')

ROOT_URLCONF = 'cincode_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cincode_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',  # 数据库主机
        'PORT': 3306,  # 数据库端口
        'USER': 'root',  # 数据库用户名
        'PASSWORD': 'mysql',  # 数据库用户密码
        'NAME': 'cincode'  # 数据库名字
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'
# LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CORS_ORIGIN_ALLOW_ALL = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'],
    # 其他设置项...
}

# JWT settings
SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=600),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=7),
    'SLIDING_TOKEN_LIFETIME_LAZY': True,
    'SLIDING_TOKEN_REFRESH_LIFETIME_LAZY': True,
    'SLIDING_TOKEN_LIFETIME_REFRESH': timedelta(days=7),
    'SLIDING_TOKEN_REFRESH_LIFETIME_HARD_LIMIT': False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
