# Generated by Django 4.2 on 2023-11-03 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article_cate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCateIntermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '文章及所属分类中间表',
                'verbose_name_plural': '文章及所属分类中间表',
                'db_table': 'article_cate_intermediate',
            },
        ),
        migrations.CreateModel(
            name='ArticleStore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('state', models.CharField(choices=[('已发布', '已发布'), ('草稿', '草稿')], max_length=10)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('pub_date', models.DateTimeField()),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cate_id', models.ManyToManyField(through='article.ArticleCateIntermediate', to='article_cate.articlecatestore')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'store_article',
            },
        ),
        migrations.AddField(
            model_name='articlecateintermediate',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articlestore'),
        ),
        migrations.AddField(
            model_name='articlecateintermediate',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_cate.articlecatestore'),
        ),
    ]
