# Generated by Django 4.2 on 2023-10-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestore',
            name='cate_id',
        ),
    ]
