# Generated by Django 4.2 on 2023-11-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecateintermediate',
            table='intermediate_article_cate',
        ),
    ]
