# Generated by Django 4.2 on 2023-10-30 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cate_article', '0002_initial'),
        ('article', '0002_remove_articlestore_cate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateArticleCate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articlestore')),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cate_article.catestore')),
            ],
            options={
                'verbose_name': '文章及所属分类中间表',
                'verbose_name_plural': '文章及所属分类中间表',
                'db_table': 'intermediate_article_cate',
            },
        ),
    ]
