# Generated by Django 4.2 on 2023-10-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_intermediatearticlecate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intermediatearticlecate',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='intermediatearticlecate',
            old_name='cate_id',
            new_name='cate',
        ),
    ]
