# Generated by Django 4.2 on 2023-10-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_article_id_intermediatearticlecate_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestore',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/'),
        ),
    ]
