# Generated by Django 4.2 on 2023-11-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_articlestore_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestore',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
