# Generated by Django 4.2 on 2023-10-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_sidebar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutsidebar',
            name='icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='layoutsidebar',
            name='index_path',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='layoutsidebar',
            name='path_level',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='layoutsidebar',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
