# Generated by Django 4.2 on 2023-10-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_sidebar', '0002_alter_layoutsidebar_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutsidebar',
            name='path_level',
            field=models.IntegerField(),
        ),
    ]
