# Generated by Django 4.2 on 2023-11-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_general_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoStaticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='The information will be released soon', max_length=255)),
                ('name_de', models.CharField(default='The information will be released soon', max_length=255, null=True)),
                ('name_en', models.CharField(default='The information will be released soon', max_length=255, null=True)),
                ('rating', models.IntegerField()),
                ('website', models.URLField()),
                ('language', models.CharField(default='zh-Hans', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_general_models.utilcity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_general_models.utilcountry')),
            ],
            options={
                'verbose_name': '展会基本信息',
                'verbose_name_plural': '展会基本信息',
                'db_table': 'store_expo_staticdata',
                'unique_together': {('language', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExpoStore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='The information will be released soon', max_length=4000)),
                ('description_de', models.TextField(default='The information will be released soon', max_length=4000, null=True)),
                ('description_en', models.TextField(default='The information will be released soon', max_length=4000, null=True)),
                ('date', models.DateField()),
                ('num_expos', models.IntegerField()),
                ('num_visit', models.IntegerField()),
                ('language', models.CharField(default='zh-Hans', max_length=20)),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='this_expo', to='exposition.expostaticdata')),
            ],
            options={
                'verbose_name': '展会',
                'verbose_name_plural': '展会',
                'db_table': 'store_expo',
            },
        ),
        migrations.CreateModel(
            name='IntermediateExpoTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposition.expostore')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_general_models.utiltheme')),
            ],
            options={
                'verbose_name': '展会及热门主题中间表',
                'verbose_name_plural': '展会及热门主题中间表',
                'db_table': 'intermediate_expo_theme',
            },
        ),
        migrations.CreateModel(
            name='IntermediateExpoSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposition.expostore')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_general_models.utilsector')),
            ],
            options={
                'verbose_name': '展会及行业中间表',
                'verbose_name_plural': '展会及行业中间表',
                'db_table': 'intermediate_expo_sector',
            },
        ),
        migrations.AddField(
            model_name='expostore',
            name='sector',
            field=models.ManyToManyField(through='exposition.IntermediateExpoSector', to='db_general_models.utilsector'),
        ),
        migrations.AddField(
            model_name='expostore',
            name='theme',
            field=models.ManyToManyField(through='exposition.IntermediateExpoTheme', to='db_general_models.utiltheme'),
        ),
        migrations.AlterUniqueTogether(
            name='expostore',
            unique_together={('language', 'name', 'date')},
        ),
    ]
