# Generated by Django 4.2 on 2023-11-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expostaticdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='expostore',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='expostaticdata',
            name='language',
        ),
        migrations.RemoveField(
            model_name='expostore',
            name='language',
        ),
    ]
