# Generated by Django 4.2 on 2023-11-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0002_alter_expostaticdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expostaticdata',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expostaticdata',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expostaticdata',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
