# Generated by Django 4.2 on 2023-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0003_alter_expostaticdata_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expostaticdata',
            name='name_zh_Hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expostore',
            name='description_zh_Hans',
            field=models.TextField(default='The information will be released soon', max_length=4000, null=True),
        ),
    ]
