# Generated by Django 4.2 on 2023-11-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0004_expostaticdata_name_zh_hans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expostore',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='expostore',
            name='description_de',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='expostore',
            name='description_en',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='expostore',
            name='description_zh_Hans',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
