# Generated by Django 4.2 on 2023-11-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0005_alter_expostore_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expostore',
            name='year',
            field=models.PositiveIntegerField(default=2023),
        ),
        migrations.AlterUniqueTogether(
            name='expostore',
            unique_together={('name', 'year')},
        ),
    ]
