# Generated by Django 4.2 on 2023-11-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0006_expostore_year_alter_expostore_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoExhibitorStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo_link', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibitor_current_year', to='exposition.expostore')),
                ('expo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expo_current_year', to='exposition.expostore')),
            ],
            options={
                'verbose_name': '展会展商列表',
                'verbose_name_plural': '展会展商列表',
                'db_table': 'store_expo_exhibitor',
            },
        ),
    ]
