# Generated by Django 4.2 on 2023-11-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_general_models', '0008_alter_utilcity_city_cn'),
        ('exposition', '0007_expoexhibitorstore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intermediateexposector',
            unique_together={('expo', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='intermediateexpotheme',
            unique_together={('expo', 'theme')},
        ),
    ]
