# Generated by Django 4.2 on 2023-11-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_en', models.CharField(max_length=255, unique=True)),
                ('country_cn', models.CharField(max_length=255, unique=True)),
                ('short_Len2', models.CharField(max_length=20, unique=True)),
                ('region', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': '国家',
                'verbose_name_plural': '国家',
                'db_table': 'util_country',
            },
        ),
        migrations.CreateModel(
            name='UtilLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_iso', models.CharField(max_length=255, unique=True)),
                ('lang_cn', models.CharField(max_length=255)),
                ('lang_code639', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '语言',
                'verbose_name_plural': '语言',
                'db_table': 'util_lang',
            },
        ),
        migrations.CreateModel(
            name='UtilTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('theme_de', models.CharField(max_length=255, null=True)),
                ('theme_en', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '热门主题',
                'verbose_name_plural': '热门主题',
                'db_table': 'util_theme',
                'unique_together': {('language', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='UtilCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_en', models.CharField(max_length=255, unique=True)),
                ('city_cn', models.CharField(max_length=255, unique=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db_general_models.utilcountry')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'util_city',
            },
        ),
        migrations.CreateModel(
            name='UtilSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
                ('sector_de', models.CharField(max_length=255, null=True)),
                ('sector_en', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=10)),
                ('parent_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db_general_models.utilsector')),
            ],
            options={
                'verbose_name': '行业',
                'verbose_name_plural': '行业',
                'db_table': 'util_sector',
                'unique_together': {('language', 'sector')},
            },
        ),
    ]
