# Generated by Django 4.2 on 2023-11-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_general_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='utilsector',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='utiltheme',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='utilsector',
            name='language',
        ),
        migrations.RemoveField(
            model_name='utiltheme',
            name='language',
        ),
    ]
