# Generated by Django 4.2 on 2023-11-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_general_models', '0003_utilsector_sector_zh_hans_utiltheme_theme_zh_hans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilsector',
            name='sector',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='utilsector',
            name='sector_de',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilsector',
            name='sector_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilsector',
            name='sector_zh_Hans',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
