# Generated by Django 4.2 on 2023-11-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_general_models', '0004_alter_utilsector_sector_alter_utilsector_sector_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilsector',
            name='sector',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='utilsector',
            name='sector_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilsector',
            name='sector_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilsector',
            name='sector_zh_Hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='utilsector',
            unique_together={('sector', 'parent_sector')},
        ),
    ]
