# Generated by Django 4.2 on 2023-11-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_general_models', '0006_utiltheme_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilsector',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utiltheme',
            name='theme',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
