# Generated by Django 4.2 on 2023-11-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_general_models', '0007_alter_utilsector_sector_alter_utiltheme_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilcity',
            name='city_cn',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
